name: quiz_app_tutorial
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  introduction_screen: ^3.0.1
  video_player: ^2.2.18
  chewie: ^1.3.0
  country_code_picker: ^3.0.0
  intl_phone_field: ^3.2.0
  intl_phone_number_input: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Bubblegum
      fonts:
        - asset: Bubblegum_Sans/BubblegumSans-Regular.ttf
        
          